//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelAccountingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_TABLE_LOGS
    {
        public int Log_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Attribute { get; set; }
    }
}
